import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";

import "./globals.css";
import { AppSpacetimeDBProvider } from "@/lib/spacetimedb/provider";
import { cn } from "@/lib/utils";
import { TRPCReactProvider } from "@/utils/trpc/client";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-mono",
        jetbrainsMono.variable,
        "dark"
      )}
    >
      <body className="min-h-full flex flex-col">
        <AppSpacetimeDBProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </AppSpacetimeDBProvider>
      </body>
    </html>
  );
}
