// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Biome,
  RockType,
  OreModifiers,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  worldId: __t.u64().name("world_id"),
  chunkX: __t.f64().name("chunk_x"),
  chunkY: __t.f64().name("chunk_y"),
  get biome() {
    return Biome;
  },
  get geology() {
    return RockType;
  },
  richness: __t.f64(),
  get oreModifiers() {
    return OreModifiers.name("ore_modifiers");
  },
  regionName: __t.string().name("region_name"),
});
