// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const World = __t.object("World", {
  id: __t.u64(),
  seed: __t.f64(),
  size: __t.f64(),
  chunkSize: __t.f64(),
  chunksWide: __t.f64(),
  chunksHigh: __t.f64(),
});
export type World = __Infer<typeof World>;

