// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddReducer from "../add_reducer";
import DeleteWorldReducer from "../delete_world_reducer";

export type AddParams = __Infer<typeof AddReducer>;
export type DeleteWorldParams = __Infer<typeof DeleteWorldReducer>;

