name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [synchronize, opened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      spacetimedb:
        image: clockworklabs/spacetime
        ports:
          - 3000:3000

    steps:
      - uses: actions/checkout@v6

      - name: Cache turbo output
        uses: actions/cache@v5
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true
          run_install: true

      - name: Install SpacetimeDB CLI
        run: |
          curl -sSf https://install.spacetimedb.com | sh -s -- -y
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run linter
        run: pnpm turbo check

      - name: Run tests
        run: pnpm turbo test

      - name: Build
        run: pnpm turbo build
        env:
          DB_FILE_NAME: ${{ vars.DB_FILE_NAME }}
          SPACETIMEDB_HOST: ${{ vars.SPACETIMEDB_HOST }}
          SPACETIMEDB_DB_NAME: ${{ vars.SPACETIMEDB_DB_NAME }}
          NEXT_PUBLIC_SPACETIMEDB_HOST: ${{ vars.NEXT_PUBLIC_SPACETIMEDB_HOST }}
          NEXT_PUBLIC_SPACETIMEDB_DB_NAME: ${{ vars.NEXT_PUBLIC_SPACETIMEDB_DB_NAME }}
